"""Module for init functionality."""

from bot.db.base import Base
from bot.db.models import (
    Ad,
    BroadcastRequest,
    Complaint,
    CoinDrop,
    Deal,
    Dispute,
    Game,
    RouletteSpin,
    Review,
    Scammer,
    ScammerEvidence,
    Service,
    ServicePurchase,
    StaffTask,
    SupportMessage,
    SupportTicket,
    TopUp,
    TopicActivityMeta,
    TopicActivityReward,
    TopicActivityStat,
    User,
    WalletTransaction,
)

__all__ = [
    "Base",
    "Ad",
    "Complaint",
    "CoinDrop",
    "Deal",
    "Dispute",
    "Game",
    "Review",
    "Service",
    "ServicePurchase",
    "Scammer",
    "ScammerEvidence",
    "SupportTicket",
    "SupportMessage",
    "BroadcastRequest",
    "RouletteSpin",
    "StaffTask",
    "TopUp",
    "TopicActivityMeta",
    "TopicActivityReward",
    "TopicActivityStat",
    "User",
    "WalletTransaction",
]
